/*DROP DATABASE SCHEMA*/
DROP DATABASE IF EXISTS  web_shopping_bd;

/*CREATE DATABASE */
CREATE DATABASE  web_shopping_bd ENCODING = 'UTF8' LOCALE = 'es_CL.UTF-8';

/*DROP USER SCHEMA*/
DROP USER IF EXISTS web_shopping_adm;

/*CREATE USER*/
CREATE USER web_shopping_adm WITH ENCRYPTED PASSWORD 'OXfl0XSA454J28I2r3yU31I1kH';

GRANT ALL PRIVILEGES ON DATABASE  web_shopping_bd to web_shopping_adm;